# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_useranswersquestion_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswersquestion',
            name='user_answer',
            field=models.FloatField(default=None, null=True),
        ),
    ]
