# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170406_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBiasGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'plain_number'), ('1', 'random_fact'), ('3', 'targeted_fact_close'), ('2', 'targeted_fact_far_off')], max_length=1)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='useranswersquestion',
            old_name='user_answer',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bias_starter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswersquestion',
            name='bias_starter_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='questionbiasgenerator',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
