# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_useranswersquestion_bias_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
