# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_explanationtexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanationtexts',
            name='stage',
        ),
        migrations.AddField(
            model_name='explanationtexts',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='explanationtexts',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
